name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      -
        name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v1.31.0
          GOLINTFLAGS='--timeout=10m' golangci-lint run
