version: '3.9'
services:
  connector:
    build:
      dockerfile: cmd/connector/Dockerfile
    image: connector
    command: ["-f", "/app/config.yml"]
    volumes:
      - ${PWD}/connector.yml:/app/config.yml
    networks:
      - protocall
  clerk:
    build:
      dockerfile: cmd/clerk/Dockerfile
    image: clerk
    command: ["-f", "/app/clerk.yml"]
    environment:
      - BUCKET_ACCESS_KEY
      - BUCKET_SECRET_KEY
      - EMAIL_KEY
      - CONNECTOR_KEY
      - YASTT_ACCESS_KEY
      - YASTT_SECRET_KEY
    volumes:
      - ${PWD}/clerk.yml:/app/clerk.yml
    ports:
      - 127.0.0.1:8080:80
    networks:
      - protocall
  frontend:
    image: nginx:latest
    volumes:
      - ${PWD}/certs:/certs
      - ${PWD}/static:/var/www/html
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:443:443
    networks:
      - protocall
    depends_on:
      - connector
  centrifugo:
    image: centrifugo/centrifugo
    command: ["centrifugo", "-c", "/centrifugo.json"]
    networks:
      - protocall
    volumes:
      - ${PWD}/centrifugo.json:/centrifugo.json
  redis:
    image: redis
    command: ["redis-server", "--save", "60", "1"]
    networks:
      - protocall
    volumes:
      - redis:/data
networks:
  protocall:
volumes:
  redis:
