ari:
  application: "protocall"
  password: "d762c28ae3dfae2f4bdcda28660165b7"
  snoopy_application: "snoopy"
  url: "http://aster.softex-team.ru:10088/ari"
  user: "telephony"
  ws_url: "ws://aster.softex-team.ru:10088/ari/events"
  account_file: "/app/accounts.json"
log:
  file: '-'
  level: debug
server:
  api_key: secret
  ip: "0.0.0.0"
  port: "80"
  domain: "localhost"
uploader:
  host: "aster.softex-team.ru"
  port: "8888"
translator:
  host: "clerk"
  port: "80"
centrifugo:
  token: "bbc53758-e786-4101-ba07-15f5b95357e1"
  api_key: "c81c1a21-f836-4c85-a261-7eecabba25f2"
  host: "centrifugo:9000"
