apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognizer-pod
  namespace: protocall
spec:
  selector:
    matchLabels:
      app: recognizer
  template:
    metadata:
      labels:
        app: recognizer
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: recognizer
        image: alphacep/kaldi-ru:latest
        ports:
        - name: recognizer
          containerPort: 2700
---
apiVersion: v1
kind: Service
metadata:
  name: recognizer-service
  namespace: protocall
spec:
  type: NodePort
  selector:
    app: recognizer
  ports:
  - name: recognizer
    port: 2700
    nodePort: 30001
    targetPort: recognizer
