apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/upstream-vhost: protocall-static.fra1.digitaloceanspaces.com
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - protocall.softex-team.ru
    secretName: protocall-example-tls
  rules:
  - host: protocall.softex-team.ru
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
