apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ExternalName
  selector:
    app: frontend
  externalName: protocall-static.fra1.digitaloceanspaces.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
