apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
spec:
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      containers:
      - name: connector
        image: connector-image
        command: ["connector", "-s", "/etc/connector/config.yml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/connector
        - name: accounts-volume
          mountPath: /connector
        ports:
        - name: connector
          containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: connector-config
      - name: accounts-volume
        configMap:
          name: accounts
      imagePullSecrets:
        - name: regcred
