recognizer:
  host: "recognizer"
  port: "2700"
storage:
  bucket: "protocall-storage"
  endpoint: "protocall-storage.fra1.digitaloceanspaces.com"
sender:
  username: "protocall@softex-team.ru"
  host: "mail.netangels.ru"
  port: 587
server:
  host: "0.0.0.0"
  port: "80"
