apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base/clerk
patchesStrategicMerge:
  - limits.yml
  - pull-secret.yml
secretGenerator:
  - name: clerk-secrets
    envs:
      - .env
configMapGenerator:
  - name: config
    files:
      - config.yml
images:
  - name: clerk-image
    newName: ghcr.io/softree-group/protocall-connector/clerk
    newTag: 0.1.0
