apiVersion: apps/v1
kind: Deployment
metadata:
  name: clerk
spec:
  selector:
    matchLabels:
      app: clerk
  template:
    spec:
      containers:
        - name: clerk
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 500m
