---
- name: Create directories if it does not exist
  ansible.builtin.file:
    path: "{{item.dest}}"
    state: directory
    mode: '0755'
  loop: "{{configs}}"

- name: Copy files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  loop: "{{configs}}"

- name: Reload porter service
  ansible.builtin.systemd:
    name: "{{service_name}}"
    enabled: yes
    masked: no
    daemon_reload: yes
    state: restarted
