name: validate

on: push

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup go enviroment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Get sources
        uses: actions/checkout@v2

      - name: Sanitize source code
        run: go vet ./...

      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
